kind: pipeline
name: default
platform:
  arch: arm64
  os: linux
steps:
- name: install-dependencies
  image: ubuntu:focal
  commands:
  - echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
  - apt update && apt dist-upgrade -y
  - apt install build-essential pkg-config libc6-dev m4 autoconf libtool libncurses-dev unzip git zlib1g-dev wget libcurl4-gnutls-dev bsdmainutils automake curl libsodium-dev libboost-dev libdb++-dev -y -q
  - ./zcutil/fetch-params-alt.sh
  - BUILD=aarch64-linux-gnu ./zcutil/build-aarch64-native-static.sh -j$(nproc)
  - file src/komodod
  - file src/komodo-cli
  - zip --junk-paths komodo-armv8 src/komodod src/komodo-cli
- name: publish
  image: plugins/github-release
  settings:
    api_key: 
      from_secret: github-api-key
    files: 
    - ./komodo-armv8.zip
    - src/komodo*
    prerelease: true
  when:
    event: tag
  
