kind: pipeline
type: docker
name: default

steps:
- name: install-dependencies
  image: arm64v8/ubuntu:focal
  commands:
  - uname -a
  - apt update
  - apt upgrade -y
  - apt install build-essential pkg-config libc6-dev m4 autoconf libtool libncurses-dev unzip git zlib1g-dev wget libcurl4-gnutls-dev bsdmainutils automake curl libsodium-dev libboost-dev libdb++-dev -y
  - pwd
  - ./zcutil/fetch-params-alt.sh
  - BUILD=aarch64-linux-gnu ./zcutil/build.sh -j4
