kind: pipeline
type: docker
name: default
platform:
  arch: arm64
  os: linux
steps:
- name: install-dependencies
  image: ubuntu:focal
  commands:
  - echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
  - apt update && apt dist-upgrade -y
  - apt install build-essential pkg-config libc6-dev m4 autoconf libtool libncurses-dev unzip git zlib1g-dev wget libcurl4-gnutls-dev bsdmainutils automake curl libsodium-dev libboost-dev libdb++-dev -y -q
  - ./zcutil/fetch-params-alt.sh
  - BUILD=aarch64-linux-gnu ./zcutil/build.sh -j$(nproc)
  - file src/komodod
  - file src/komodo-cli
  - tar -cjvf armv8.tar.gz src/komodod src/komodo-cli
---

kind: pipeline
name: default1

steps:
- name: publish
  image: plugins/github-release
  settings:
    api_key: drone-ci
    files: armv8.tar.gz
  checksums:
    - md5
    - sha256
  when:
    event: tag
  
