kind: pipeline
type: docker
name: linux-armv8

platform:
  arch: arm64
  os: linux

steps:
- name: install-dependencies
  image: arm64v8/ubuntu:latest
  commands:
  - uname -a
  - pwd
  - apt install build-essential pkg-config libc6-dev m4 autoconf libtool libncurses-dev unzip git zlib1g-dev wget libcurl4-gnutls-dev bsdmainutils automake curl libsodium-dev libboost-dev libdb++-dev -y

- name: zcash-fetch-params
  image: arm64v8/ubuntu:latest
  commands:
  - ./zcutil/fetch-params-alt.sh


- name: build
  image: arm64v8/ubuntu:latest
  commands:
  - BUILD=aarch64-linux-gnu ./zcutil/build.sh -j4
