# we are using separate workflow because CI producing test binaries with CPPFLAGS=-DTESTMODE

name: Komodo CD test releases


on:
  push:
    branches:
    - beta
    - dev
    - research
    - arm64-cross

jobs:

  linux-build:
    name: Linux Build
    # using there as old release as possible with GHA worker to provide better compatibility
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install deps (Linux)
        run: |
          sudo apt-get update  # prevents repo404 errors on apt-remove below
          sudo apt-get remove php* msodbcsql17 mysql* powershell dotn*
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get upgrade -y
          sudo apt-get install -q \
                 build-essential \
                 pkg-config \
                 libc6-dev \
                 m4 \
                 libsodium-dev \
                 libboost-dev \
                 libdb++-dev \
                 g++-multilib \
                 autoconf \
                 libtool \
                 libncurses-dev \
                 unzip \
                 zip \
                 git \
                 zlib1g-dev \
                 wget \
                 bsdmainutils \
                 automake \
                 curl \
                 python3 \
                 python3-dev \
                 python3-setuptools \
                 python3-pip \
                 libcurl4-openssl-dev \
                 libssl-dev -y

      - name: Build (Linux)
        env:
          CONFIGURE_FLAGS: --with-gcc-arch=x86-64
        run: |
          ./zcutil/build.sh -j$(nproc)
          zip --junk-paths komodo-linux src/komodod src/komodo-cli
      - name: Upload komodo-linux.zip as artifact
        uses: actions/upload-artifact@v1
        with:
          name: komodo-linux
          path: ./komodo-linux.zip

  linux-aarch64-cross:
    name: Linux ARM64 cross
    # using there as old release as possible with GHA worker to provide better compatibility
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install deps (Linux)
        run: |
          sudo apt-get update  # prevents repo404 errors on apt-remove below
          sudo apt-get remove php* msodbcsql17 mysql* powershell dotn*
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get upgrade -y
          ./zcutil/fetch-params-alt.sh
          sudo apt-get install -q \
            build-essential \
            pkg-config \
            libc6-dev \
            m4 \
            autoconf \
            libtool \
            libncurses-dev \
            zip \
            unzip \
            git \
            zlib1g-dev \
            wget \
            linux-libc-dev-arm64-cross \
            g++-aarch64-linux-gnu \
            binutils-aarch64-linux-gnu \
            libcurl4-gnutls-dev \
            bsdmainutils \
            automake \
            curl \
            libsodium-dev \
            libboost-dev \
            libdb++-dev -y

      - name: Build (ARM64-cross)
        env:
          HOST: aarch64-linux-gnu
        run: |
          ./zcutil/build.sh -j$(nproc)
          zip --junk-paths komodo-aarch64 src/komodod src/komodo-cli
      - name: Upload komodo-aarch64.zip as artifact
        uses: actions/upload-artifact@v1
        with:
          name: komodo-aarch64
          path: ./komodo-aarch64.zip
          
  osx-build:
    name: OSX Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deps (macOS)
        run: |
          brew update
          brew upgrade
          brew tap discoteq/discoteq; brew install flock
          brew install autoconf autogen automake
          brew install gcc@8
          brew install binutils
          brew install protobuf
          brew install coreutils
          brew install wget
          brew install python3
          brew install gmp
          ./zcutil/fetch-params-alt.sh
      - name: Build (macOS)
        env:
          CONFIGURE_FLAGS: --with-gcc-arch=x86-64
        run: |
          ./zcutil/build-mac.sh -j$(nproc)
          zip --junk-paths komodo-osx src/komodod src/komodo-cli
      - name: Upload komodo-osx.zip as artifact
        uses: actions/upload-artifact@v1
        with:
          name: komodo-osx
          path: ./komodo-osx.zip

  windows-build:
    name: Windows Build (mingw)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install deps (Windows)
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update  # prevents repo404 errors on apt-remove below
          sudo apt-get remove php* msodbcsql17 mysql* powershell containernetworking-* containers* dotn*
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install build-essential pkg-config libc6-dev m4 g++-multilib autoconf libtool \
                               libncurses-dev unzip wget bsdmainutils automake libboost-all-dev libssl-dev \
                               libprotobuf-dev protobuf-compiler libqrencode-dev libdb++-dev ntp ntpdate nano \
                               software-properties-common curl libevent-dev libcurl4-gnutls-dev cmake clang \
                               libsodium-dev ncurses-dev git python3 python3-zmq zlib1g-dev mingw-w64 -y
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env
          rustup target add x86_64-pc-windows-gnu
          sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
          sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
          ./zcutil/fetch-params-alt.sh
      - name: Build (Windows)
        env:
          CONFIGURE_FLAGS: --with-gcc-arch=x86-64
        run: |
          ./zcutil/build-win.sh -j$(nproc)
          zip --junk-paths komodo-win src/komodod.exe src/komodo-cli.exe
      - name: Upload komodo-win.zip as artifact
        uses: actions/upload-artifact@v1
        with:
          name: komodo-win
          path: ./komodo-win.zip      

  publish-release:
      name: Publishing CD releases
      runs-on: ubuntu-latest
      needs: [linux-build, osx-build, windows-build, linux-aarch64-cross]
      steps:
        - name: Download komodo-linux.zip
          uses: actions/download-artifact@v1
          with:
            name: komodo-linux
        - name: Download komodo-aarch64.zip
          uses: actions/download-artifact@v1
          with:
            name: komodo-aarch64
        - name: Download komodo-osx.zip
          uses: actions/download-artifact@v1
          with:
            name: komodo-osx
        - name: Download komodo-win.zip
          uses: actions/download-artifact@v1
          with:
            name: komodo-win

        - name: Extract branch name
          shell: bash
          run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          id: extract_branch

        - name: Shortify commit sha
          shell: bash
          run: echo "##[set-output name=sha_short;]$(echo ${GITHUB_SHA::7})"
          id: shortify_commit

        - name: Create Release
          id: create_release
          uses: actions/create-release@latest
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: cd_release_${{ steps.shortify_commit.outputs.sha_short }}_${{ steps.extract_branch.outputs.branch }}
            release_name: CD Release ${{ steps.shortify_commit.outputs.sha_short }} ${{ steps.extract_branch.outputs.branch }}
            draft: false
            prerelease: true
        - name: Upload Linux Release Asset
          id: upload-linux-release-asset 
          uses: actions/upload-release-asset@latest
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
            asset_path: komodo-linux/komodo-linux.zip
            asset_name: komodo_${{ steps.shortify_commit.outputs.sha_short }}_${{ steps.extract_branch.outputs.branch }}_linux.zip
            asset_content_type: application/zip
        - name: Upload OSX Release Asset
          id: upload-osx-release-asset 
          uses: actions/upload-release-asset@latest
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
            asset_path: komodo-osx/komodo-osx.zip
            asset_name: komodo_${{ steps.shortify_commit.outputs.sha_short }}_${{ steps.extract_branch.outputs.branch }}_osx.zip
            asset_content_type: application/zip
        - name: Upload Windows Release Asset
          id: upload-windows-release-asset 
          uses: actions/upload-release-asset@latest
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
            asset_path: komodo-win/komodo-win.zip
            asset_name: komodo_${{ steps.shortify_commit.outputs.sha_short }}_${{ steps.extract_branch.outputs.branch }}_win.zip
            asset_content_type: application/zip
